added tests for home page and dividend calculator page
UserOk007/sgs-automation pull request #3
Opened 2024-08-15 17:51 UTC by UserOk007

2024-08-16 08:33 UTC, Olha-Vasylets commented on cypress/e2e/dividendCalculator.cy.js
> +        cy.get(selectors.scriptDividend.buttonTextClass).contains(testData.dividendCalculator.dontAgreeButton).click({force: true});
{force: true} why is it needed here?

2024-08-16 08:39 UTC, UserOk007 commented on cypress/e2e/dividendCalculator.cy.js
> +        cy.get(selectors.scriptDividend.buttonTextClass).contains(testData.dividendCalculator.dontAgreeButton).click({force: true});
The system showed an error and it didn't click on the button. There was a recommendation in cypress running tests area to add {force: true}. After adding, it started to work

2024-08-16 10:04 UTC, Olha-Vasylets requested changes
Please correct all the points we discussed. And remember, you're a rock anyway :)

2024-09-02 08:31 UTC, Olha-Vasylets commented on cypress/e2e/homePage.cy.js
> +    });
**let's try to add a slightly more readable structure?** 

```
    cy.get(selectors.homePage.countryValueInCountrySelectionMenu)
        .eq(27)
        .invoke('removeAttr', 'target')
        .click();

    cy.get(selectors.homePage.currentCountryLanguageInFooter)
        .eq(0)
        .should('contain', testData.homePage.currentCountry);
    cy.get(selectors.homePage.currentCountryLanguageInFooter)
        .eq(1)
        .should('contain', testData.homePage.currentLanguage);

```
 _:) yes, it is longer but easier to read/watch_

2024-09-02 08:44 UTC, Olha-Vasylets requested changes
please break into lines

2024-09-13 08:02 UTC, UserOk007 reviewed
@Olha-Vasylets  Hi! I committed changes to the previous branch. Using chatGPT I tried to cancel my commit to add it to the new branch but it was not successful. All my last changes are in this commit. Please review.

2024-09-13 08:41 UTC, Olha-Vasylets approved these changes

2024-09-13 08:45 UTC, merged